component: scf # 必填内容
name: ${env:COMPONENT_NAME}
org: ''
app: ''
stage: production
inputs:
  name: ${env:SCF_NAME}
  src: ./dist
  runtime: Nodejs12.16
  region: ${env:SCF_REGION}
  description: ${env:SCF_DESCRIPTION}
  handler: index.main_handler
  memorySize: ${env:SCF_MEMORY_SIZE}
  timeout: 900
  events:
    - timer: # 定时触发器
        parameters:
          # name: timer # 触发器名称，默认timer-${name}-${stage}
          name: daily_bili_timer # 若要使用scf随机执行请勿修改触发器名
          cronExpression: ${env:BILI_DAILY_CRON_EXPRESSION} # 每天22点43分55秒触发
          enable: ${env:BILI_DAILY_RUN}
          argument: 日常任务
  environment:
    variables:
      TENCENT_SECRET_ID: ${env:TENCENT_SECRET_ID}
      TENCENT_SECRET_KEY: ${env:TENCENT_SECRET_KEY}
  # For more information: https://github.com/serverless-components/tencent-scf/blob/master/docs/configure.md
