component: scf # 必填内容
name: ap-chengdu_default_biliExp
org: ''
app: biliExp
stage: production
inputs:
  name: biliExp
  src: ./dist
  runtime: Nodejs12.16
  region: ap-chengdu
  description: bilibili小工具
  handler: index.main_handler
  memorySize: 64
  timeout: 900
  events:
    - timer: # 定时触发器
        parameters:
          # name: timer # 触发器名称，默认timer-${name}-${stage}
          cronExpression: '${env.BILI_DAILY_CRON_EXPRESSION}' # 每天22点43分55秒触发
          enable: true
          argument: 日常任务
    - timer: # 定时触发器
        parameters:
          name: jury-timer # 风纪委员触发
          cronExpression: '45 3/8 11-15 * * * *' # 用12-16这几个小时来执行风纪委员任务
          enable: ${env.BILI_JURY_VOTE}
          argument: 评审任务
# For more information: https://github.com/serverless-components/tencent-scf/blob/master/docs/configure.md
