name: bilibili-task

on:
  workflow_dispatch: # 手动触发
  # schedule: # 计划任务触发
    # - cron: '5 15 * * *'
    # cron表达式，时区是UTC时间，比我们晚8小时，要用我们的时间减去8小时后填上去，如上所表示的是每天23点5分
    # 建议每个人都修改下时间！不要使用默认时间！最好不要设定在整点，错开峰值，避免大量G站同一个IP在相同时间去请求B站接口，导致IP被禁！

jobs:
  run-bilibili-tool:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      # 输出IP
      - name: IP
        run: sudo curl ifconfig.me

      # 设置服务器时区为东八区
      - name: Set time zone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      # 检出
      - name: Checkout
        uses: actions/checkout@v2

      # 环境
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1

      # 安装依赖
      - name: Install dependencies
        run: /
          npm install -g typescript
          npm install

      # 构建应用
      - name: Build APP
        run: npm run build

      # 运行
      - name: Run APP
        env:
          USERID: ${{secrets.USERID}}
          SESSDATA: ${{secrets.SESSDATA}}
          BILIJCT: ${{secrets.BILIJCT}}
          BILIJCT: ${{secrets.BILI_JCT}} # 为了兼容 GitHub Secrets 经常会被填错
          BILI_TARGET_COINS: ${{secrets.BILI_TARGET_COINS}}
          BILI_API_DELAY: ${{secrets.BILI_API_DELAY}}
          BILI_CUSTOMIZE_UP: ${{secrets.BILI_CUSTOMIZE_UP}}
          USER_AGENT: ${{secrets.USER_AGENT}}
        run: npm run start
