name: deploy_tencent_sls

on:
  push:
    branches:
      - main

env:
  TENCENT_SECRET_ID: ${{secrets.TENCENT_SECRET_ID}}
  TENCENT_SECRET_KEY: ${{secrets.TENCENT_SECRET_KEY}}
  SERVERLESS_PLATFORM_VENDOR: tencent

jobs:
  deploy-bilibili-tool:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      # 输出IP
      - name: IP
        run: sudo curl ifconfig.me

      # 设置服务器时区为东八区
      - name: Set time zone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      # 检出
      - name: Checkout
        uses: actions/checkout@v2

      # 环境
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1

      # 安装依赖
      - name: Install dependencies
        run: |
          npm install -g typescript serverless
          npm install

      # 构建应用
      - name: Build APP
        run: npm run build

      - name: 生成.env文件存储某些隐私数据
        run: |
          if [ -z "$TENCENT_SECRET_ID" ]; then
          echo "部署至腾讯云需要填写TENCENT_SECRET_ID和TENCENT_SECRET_KEY两个secrets"
          exit -1
          fi
          mv .env.example .env
          echo USERID=${{secrets.USERID}} >> .env
          echo SESSDATA=${{secrets.SESSDATA}} >> .env
          echo BILIJCT=${{secrets.BILIJCT}} >> .env
          echo BILI_JCT=${{secrets.BILI_JCT}} >> .env

      # 部署
      - name: Deploy APP
        run: npm run deploy
