name: deploy_tencent_sls

on:
  # push:
  # branches:
  # - main
  schedule: # 计划任务触发
    - cron: '5 16 * * *' # 每天0点5分执行(存在误差)
  workflow_dispatch: #手动触发

env:
  TENCENT_SECRET_ID: ${{secrets.TENCENT_SECRET_ID}}
  TENCENT_SECRET_KEY: ${{secrets.TENCENT_SECRET_KEY}}
  SERVERLESS_PLATFORM_VENDOR: tencent

jobs:
  deploy-bilibili-tool:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    environment: Develop

    steps:
      # 判断是否暂停运行
      - name: isStop ?
        env:
          STOP_RUN: ${{secrets.STOP_RUN}}
        run: |
          if [ $STOP_RUN ]; then
          echo "用户设置停止运行程序"
          exit -1
          fi

      # 输出IP
      - name: IP
        run: sudo curl ifconfig.me

      # 设置服务器时区为东八区
      - name: Set time zone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      # 检出
      - name: Checkout
        uses: actions/checkout@v2

      # 环境
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # 安装依赖
      - name: Install dependencies
        timeout-minutes: 5
        run: |
          npm install -g typescript serverless
          npm install

      # 构建应用
      - name: Build APP
        run: npm run build

      - name: 生成config.temp.json文件
        timeout-minutes: ${{secrets.TIMEOUT_MINUTES || 15}} # 超时时间(分钟)
        run: |
          if [ -z "$TENCENT_SECRET_ID" ]; then
          echo "部署至腾讯云需要填写TENCENT_SECRET_ID和TENCENT_SECRET_KEY两个secrets"
          exit -1
          fi
          string="${{ secrets.BILI_CONFIG }}"
          if [ -n "$string" ]; then
          echo "$string" >> ./config/config.temp.txt
          echo "成功将secrets(BILI_CONFIG)内容输出到配置文件config.temp.txt"
          node ./tools/processConfig.js
          echo "成功转换成config.temp.json"
          exit 0
          fi

      # 部署
      - name: 部署多用户程序
        run: npm run deploy:muilt
