name: gh-release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-docker:
    if: github.repository == 'catlair/BiliTools'
    runs-on: ubuntu-latest
    environment: Build
    steps:
      - name: set Docker tag
        run: echo DOCKER_TAGS=${{ github.ref  }} | sed -e "s/refs\/tags\/v//g"  >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: ${{ secrets.DOCKER_PLATFORMS || 'linux/amd64,linux/arm64' }}
          tags: catlair/bilitools:latest,catlair/bilitools:${{ env.DOCKER_TAGS }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  release:
    needs: build-docker
    if: github.repository == 'catlair/BiliTools'
    runs-on: ubuntu-latest
    environment: Build
    steps:
      - name: Copy dist
        run: |
          docker run -id --rm --name copy_dist catlair/bilitools:latest sh
          docker cp copy_dist:/usr/src/app/node_modules .
          docker cp copy_dist:/usr/src/app/dist .
          mv node_modules dist
      - name: ZIP
        run: |
          cd dist
          zip -r -q tencent_scf.zip *
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/tencent_scf.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
