name: gh-release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-docker:
    if: github.repository == 'catlair/BiliTools'
    runs-on: ubuntu-latest
    environment: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: set Docker version tag
        run: |
          echo DOCKER_TAG1=${{ github.ref  }} | sed -e "s/refs\/tags\/v//g" >> $GITHUB_ENV
      - name: set Docker latest tag
        run: |
          echo DOCKER_TAG2=${{ contains(env.DOCKER_TAG1, 'rc') && 'test' || 'latest' }} >> $GITHUB_ENV
          sed -i 2a\echo\ version=${{ env.DOCKER_TAG1 }} docker-entrypoint.sh
          echo ${{ env.DOCKER_TAG1 }} >> src/version.txt
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: ${{ secrets.DOCKER_PLATFORMS || 'linux/amd64,linux/arm64/v8' }}
          tags: catlair/bilitools:${{ env.DOCKER_TAG2 }},catlair/bilitools:${{ env.DOCKER_TAG1 }}
      - name: Image digest
        run: |
          echo "镜像对应hash"
          echo ${{ steps.docker_build.outputs.digest }}
  release:
    if: github.repository == 'catlair/BiliTools'
    runs-on: ubuntu-latest
    environment: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: |
          rm yarn.lock
          jq '( .optionalDependencies )' package.json > optionalDependencies.json
          jq 'del( .optionalDependencies )' package.json > temp.json
          mv temp.json package.json
          yarn install
          npm install -g rollup
      - name: set Docker version tag
        run: |
          echo DOCKER_TAG1=${{ github.ref  }} | sed -e "s/refs\/tags\/v//g" >> $GITHUB_ENV
          echo DOCKER_TAG2=${{ contains(env.DOCKER_TAG1, 'rc') && 'test' || 'latest' }} >> $GITHUB_ENV
      - name: Build and ZIP CFC
        run: |
          yarn build:baidu
          echo ${{ env.DOCKER_TAG1 }} >> dist/version.txt
          cp -rf ./tools/ ./package*.json yarn.lock ./docker/.yarnclean ./node_modules/ ./dist/
          cd dist
          npm prune --production
          yarn autoclear
          mv index.cfc.js cfc
          rm -rf index*.js tools package*.json yarn.lock .yarnclean
          mv cfc index.js
          zip -r -q ../baidu_cfc.zip .
      - name: Build Babel
        run: |
          yarn build
          echo ${{ env.DOCKER_TAG1 }} >> dist/version.txt
          cp config/config.single.json dist/config/config.json
          cd dist
          mv index.js index.local.js
          mv index.scf.js ../
          mv index.fc.js ../
      - name: ZIP SCF
        run: |
          cp -rf ./tools/ ./package*.json yarn.lock ./docker/.yarnclean ./node_modules/ ./dist/
          mv ./index.scf.js ./dist/index.js
          cd dist
          yarn add tencentcloud-sdk-nodejs
          npm prune --production
          yarn autoclear
          rm -rf tools package*.json yarn.lock .yarnclean
          zip -r -q ../tencent_scf.zip *
          rm -rf node_modules
      - name: ZIP FC
        run: |
          cp -rf ./tools/ ./package*.json yarn.lock ./docker/.yarnclean ./node_modules/ ./dist/
          mv ./index.fc.js ./dist/index.js
          cd dist
          # yarn add @alicloud/fc2 # 自带 fc2
          npm prune --production
          yarn autoclear
          rm -rf tools package*.json yarn.lock .yarnclean
          zip -r -q ../aliyun_fc.zip *
      - name: Build Rollup
        run: |
          cat package.json | jq .optionalDependencies="$(cat optionalDependencies.json)" > demo.json
          mv demo.json package.json
          yarn
          yarn build:rollup
          cp dist/rollup gh-release -r
      - name: Commit files to gh-release branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'release: Commit from GitHub Actions (gh-release)'
          branch: gh-release
          commit_options: '--no-verify --signoff'
          file_pattern: gh-release/**
          push_options: '--force'
          skip_fetch: true
          skip_checkout: true
          create_branch: true
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            tencent_scf.zip
            aliyun_fc.zip
            baidu_cfc.zip
            gh-release/index.js
            gh-release/cat_bili_ql.js
          draft: false
          prerelease: ${{ env.DOCKER_TAG == 'test' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
